### ISSUE TITLE
View All Posts

### ISSUE THREAD

**Issue by hannahhall** [nss-day-cohort-48/rare-client-boastful-bulldogs#12]
As a reader, I would like to see a list of all the Posts so that I can choose a post that seems interesting to read.

**Given** the user is in the Rare application  
**When** they select the `Posts` menu option  
**Then** they should be directed to the Posts list page  
**And** each post in the list should display the title, author and category  
**And** the list should ONLY contain approved Posts  
**And** the list should ONLY contain Posts with a publication date that is in the past  
**And** the list should be in order of publication date with the most recent on top

**Comment by gqgonzales** [comment]
1. FE: Build out `PostList.js` utilizing sort and filter conditionals. 
-------------------
2. BE: (postlist.js ? "go about your day! : "Write do_GET where resource =  'posts' in `requesthandler.py`, then build `posts.py` and write SELECT SQL statements.")
