### ISSUE TITLE
View Current User's Posts

### ISSUE THREAD

**Issue by hannahhall** [nss-day-cohort-48/rare-client-boastful-bulldogs#4]
As an author, I would like to see a list of all the Posts I have written so that I can easily view, edit, delete, publish or unpublish them.

**Given** the user is in the Rare application  
**When** they select the `My Posts` menu option  
**Then** they should be directed to the "My Posts" list page  
**And** the page should display ALL the Posts authored by the logged-in user  
**And** each post in the list should display the title, author and category  
**And** the list should be in order of creation date with the most recent on top

**Comment by gqgonzales** [comment]
1. FE: Build `Post.js` and `PostList.js`
2. FE: Amend <Link> in Navbar to redirect user to appropriate `PostList` view
3. BE: Write fetch calls (do_GET) and appropriate SQL queries (SELECT ... FROM) 
4. FE: Verify correct `Posts` columns are imported from SQL 
5. FE: Filter so only posts by logged-in user are displayed
