### ISSUE TITLE
View Post Details

### ISSUE THREAD

**Issue by hannahhall** [nss-day-cohort-48/rare-client-boastful-bulldogs#5]
As a reader, I would like to see the content of a Post so I can read it.

**Given** a user is viewing a list of Posts  
**When** they select a post to read  
**Then** they should be directed to a Post Detail page that shows the Post Details.

Post Details include:

* Title
* Header image (if exists)
* Content
* Publication date (MM/DD/YYYY)
* Author's Display Name

**Comment by gqgonzales** [comment]
1. FE: Create new `PostDetail` module
2. BE: Write do_GET (post_id), and SQL statements (SELECT ... FROM)
3. FE: Don't worry about buttons, tags, or anything else for now! Focus on Title, Header image (if exists), Content, Publication date (MM/DD/YYYY), Author's Display Name
