### ISSUE TITLE
Create a Tag

### ISSUE THREAD

**Issue by hannahhall** [nss-day-cohort-48/rare-client-boastful-bulldogs#8]
As an author I would like to be able to create a new Tag so that I can better classify my posts.

**Given** an author is on the Tag list page  
**When** they select the `Create Tag` button  
**Then** they should be directed to a form in which they can enter a new Tag name  

**Given** an author has entered a Tag name  
**When** they click the `Save` button  
**Then** a new Tag should be saved to the database  
**And** the author should be directed to the Tag list page

**Comment by gqgonzales** [comment]
1. FE: Build `tags` directory and populate it with `Tag.js`, `TagLists.js`, `Tags.css`, and `TagsProvider.js`
2. BE: Write do_GET and do_POST in `requesthandler.py`,  then build `tags.py` and write SELECT and INSERT SQL statements (hint: you'll need to join the `Posts` and `Tags` tables using `WHERE` statements! )
